### PR TITLE
Added follows repo

### LINKED ISSUE #244: As a developer I would like to move the follows repo methods into its own repository and create a model class for it
- [x] Follows has its own repository with the methods currently located in the userRepository
- [x] Follows class exists in the Model folder

### PR DESCRIPTION
**Pull request by AlexanderLolk**
Moved follows out from user and give follows its own repo

Resolves #244

### CODE REVIEW

**Review by Haruyzal — APPROVED** [review]
Great changes for more separation of concerns! Approved under the assumption that the integration tests will be fixed on another PR.

**Review by Slug-Boi — CHANGES_REQUESTED** [review]
Looks like a good move like we talked about. Only problem is that some of the integration tests are still trying to use the repo methods that were moved out of user repository so we should probably fix that before doing anything else 

See the failed test action on GitHub for more info

**Comment by Alex-itu** [comment]
> Looks like a good move like we talked about. Only problem is that some of the integration tests are still trying to use the repo methods that were moved out of user repository so we should probably fix that before doing anything else
> 
> See the failed test action on GitHub for more info

I have looked at 

> Looks like a good move like we talked about. Only problem is that some of the integration tests are still trying to use the repo methods that were moved out of user repository so we should probably fix that before doing anything else
> 
> See the failed test action on GitHub for more info

I have fixed the test, so if you can, please look at it again

**Review by JonasSkjodt — APPROVED** [review]
Looks good after the tests were fixed.Approved

**Review by Slug-Boi — APPROVED** [review]

**Pull request merged**
