### PR TITLE
Fix tests

### LINKED ISSUE #186: As a developer i want the tests to be runable
After updates to the database repos the tests are no longer runable. These should be refactored to a accommodate the changes.

Acceptance:
- [x] The tests build and excecute the way they are intended when running `dotnet test`

### PR DESCRIPTION
**Pull request by August-Brandt**
This changes the tests so that they fit with the new repo designs and are actually runable
Resolves #186

### CODE REVIEW

**Review by Slug-Boi — APPROVED** [review]
Tests seem to run fine and good work on the dotnet 7 downgrade so we dont get issues with building later

**Review by Haruyzal — APPROVED** [review]
Good work. 😊 

Approved with the assumption that we're moving tests around into their respective, correct files (i.e. `CreateAuthorInDatabase_Doesn'tExist` into integration tests) in a different pull request.

**Review by JonasSkjodt — APPROVED** [review]
Looks good, approved

**Review by Alex-itu — APPROVED** [review]
Nice job with the tests, approve.

**Pull request merged**
