### PR TITLE
Warnings cleanup

### PR DESCRIPTION
**Pull request by Alex-itu**
Added marks so that the compile understand that the possible null reference warnings are being handled. This should clear most of the warnings for our project.

### CODE REVIEW

**Review by JonasSkjodt — APPROVED** [review]
Looks good! Well done.

**Comment by Slug-Boi** [comment]
I will try running it on a unix system and see if i get warnings then I'll approve

**Review by Slug-Boi — APPROVED** [review]
It looks like all the warnings are fixed. Good job!

**Review by August-Brandt — APPROVED** [review]
Nice job

**Pull request merged**
