### PR TITLE
Dockerize project so it runs with docker compose and updated readme

### LINKED ISSUE #255: As a developer I would like the project to run via a docker compose command for ease of use for running the program and later use by tests
Acceptance:
- [x] Program includes a Dockerfile and docker-compose.yml file
- [x] These files can be ran with docker compose up to run the program
- [x] A bash script for ease of certificate creation
- [x] An updated readme file

### PR DESCRIPTION
**Pull request by Slug-Boi**
### This was a huge undertaking but the highly awaited feature of being able to run the program using docker compose is finally here

This branch Resolves #255 

This branch was almost entirely created by myself (with the help of google of course) with the generous help at times of mental anguish from @JonasSkjodt @Haruyzal 

Huge thank you to @albe2669 for helping fix a lot of the late kinks and bugs when trying to finish up this branch and for helping me figure out the fix to the certificate issue so that I could rebase our own code to finally have it all working

This branch has cost me at least 5 years of life expectancy but has also taught me a lot about the wonderful world of Docker 
 
Edit: after a small group discussion this branch will be presented at some point before handin date for the project so that everybody that isn't me understands what has happened. People should still review the code to just get an idea of what is on this branch then I will explain at this presentation what is actually happening =)

### CODE REVIEW

**Comment by Slug-Boi** [comment]
Fun fact that codefactor issue is unsolveable I have tried like 6 times now its just not there on the branch at all but apparently the commit its looking at has it. Great stuff

**Comment by August-Brandt** [comment]
There seams to be a lot of problems with the tests.

image

**Review by Alex-itu — APPROVED** [review]
Really cool, With this we wont have to worry about what people have install on their computer, as long they have docker that is. Nice job and Approved!

**Review by Haruyzal — APPROVED** [review]
I trust that this works - AKA approved, but would love a walkthrough.

**Review by JonasSkjodt — APPROVED** [review]
Lots of things I've never seen before, really cool. Should be treat to do it like this instead. Approved

**Pull request merged**
