### PR TITLE
Implemented EF with Repository Pattern, DbContext, and LINQ

### LINKED ISSUE #68: 1.d) As a developer I would like to seed the database using the DbInitializer.cs file
Acceptance:
- Database has the data stored from the DBInitializer file
- The database runs this seeding process when creating a new database

### LINKED ISSUE #69: 1.c ) As a dev, I'd like to create DTOs to transport info to our views for more selective display choices
DTO: Data Transfer Objects.

Create a DTO-record with Cheeps, consisting of author-name, message, and publishing date (timestamp).

**Acceptance criteria:**
- The new DTO can display author-name, message and publishing date as strings.

Co-authored by Theis <thph@itu.dk>

### LINKED ISSUE #70: 1.b)

### LINKED ISSUE #78: As a developer I would like to refactor the SQL db code using LINQ OR extension-methods.
Acceptance: 
- SQLite3 is no longer present in SimpleDB and is instead called using LINQ methods or extension-methods.
- Migration files are present in the project with all the updates to the database

### PR DESCRIPTION
**Pull request by Haruyzal**
Repository pattern: Updated ```IDatabaseRepository<T>``` and created ```CheepRepository<Cheep>``` and ```AuthorRepository<Author>```.
Resolves #70 

DTO: We had already implemented DTOs as record ```CheepViewModel(Author:string, Message:string, Timestamp:string)```
Resolves #69 

DbContext & DbInitializer
Created ```ChirpDBContext``` and refactored files such as ```CheepService``` and ```DBFacade``` to work with our DbContext. Our DbContext is being seeded by the data from ```DbInitializer.cs```.
Resolves #68 

Connected the Repositories and DBFacade by removing direct SQL code and instead use LINQ.
Resolves #78

### CODE REVIEW

**Comment by Haruyzal** [comment]
Please ignore the .Net Build and Test not working, as it seems I've pulled the old IntegrationTests.cs :)

**Review by Slug-Boi — APPROVED** [review]
Was present when we did this as a group. Looks great. Approved for merge

**Review by JonasSkjodt — APPROVED** [review]
Well done, good work. The tests are not up-to-date on this branch but they are on main.

**Review by August-Brandt — APPROVED** [review]
All looks good. Let's merge

**Pull request merged**
