### PR TITLE
Refactor server interaction into it's own class with an interface

### PR DESCRIPTION
**Pull request by August-Brandt**
To ensure separation of concerns, logic for interaction between client and server has been put in it's own class, which can then be used in `Program.cs` when posting and reading cheeps. 
Functionality is the same.
New `IServerInteraction` interface and `ClientServerInteraction` class might also be usefull in tests to avoid repeating  code.

### CODE REVIEW

**Review by Alex-itu — APPROVED** [review]
Very nice, good job with moving the code to some better places. Love it.

**Review by Slug-Boi — APPROVED** [review]
Looks great really like that its separated now. Great job August!

**Review by Slug-Boi — CHANGES_REQUESTED** [review]
Turns out the tests dont work now so I'm changing my approval back. There seems to be a namespace issue

**Review by Alex-itu — CHANGES_REQUESTED** [review]
Namespaces seems to be wrong

**Review by Alex-itu — APPROVED** [review]
I love it again

**Pull request merged**
