### PR TITLE
Integration tests with SQLite database stored in-memory

### LINKED ISSUE #94: 1.a) As a developer, I would like to use In-memory SQLite Database for Testing
Use ef core in-memory database for testing. Meaning that a database gets created for each tests.

Acceptance:
- Have a temp database
- the temp database getting delete and created at each test

### PR DESCRIPTION
**Pull request by JonasSkjodt**
Resolves #94

### CODE REVIEW

**Review by Alex-itu — APPROVED** [review]
I approve this merge.

**Review by Slug-Boi — APPROVED** [review]
Looks like a good implementation of the in mem tests. Really cool approved for merge

**Review by August-Brandt — CHANGES_REQUESTED** [review]
`InMemoryDatabase_ShouldNotPersistData` and `InMemoryDatabase_ShouldNotPersistData_test2` are not descriptive names for tests. This should insteed be someting like `AddingAuthorsWithContextAddsToDatabase`. The name of the test should describe what it tests.

**Comment by JonasSkjodt** [comment]
> `InMemoryDatabase_ShouldNotPersistData` and `InMemoryDatabase_ShouldNotPersistData_test2` are not descriptive names for tests. This should insteed be someting like `AddingAuthorsWithContextAddsToDatabase`. The name of the test should describe what it tests.

Great suggestion, two methods have been name changed to fit a better standard. While we were at it, all warnings were cleared in the integration tests.

**Pull request merged**
