### PR TITLE
Data models for entities Author and Cheep

### LINKED ISSUE #67: 1.a) As a developer I would like to create a data model for chirp.razor
Create the correct data model for the chirp.razor app.

Acceptance
- Should consist of two classes: Cheep and Author.
- For now, an author has a Name and an Email adresses (both are strings)
- A cheep contains a Text and a Timestamp. Text is a string and TimeStamp is a DateTime
-  Each cheep refers to its Author and each author keeps a reference to all its cheeps

Note: Do not convert last week's SQL schema into a data model via automatic tooling.

### PR DESCRIPTION
**Pull request by Haruyzal**
Resolves #67

### CODE REVIEW

**Review by Slug-Boi — APPROVED** [review]
Looks like a good step towards changing the DB model from direct SQL to extension methods

**Review by JonasSkjodt — APPROVED** [review]
great job, approved.

**Review by Alex-itu — APPROVED** [review]
I argee with these changes

**Review by August-Brandt — APPROVED** [review]
Looks very nice

**Pull request merged**
