### PR TITLE
Create database tests with containers

### PR DESCRIPTION
**Pull request by August-Brandt**
Adds test for database with docker testcontainers

### CODE REVIEW

**Review by Haruyzal — COMMENTED** [review]
Is it still supposed to run .Net7 ? :)
`Project Chirp.Infrastructure is not compatible with net7.0 `

**Comment by August-Brandt** [comment]
The target framwork is now .net8. Other updates should be fixed when merging to main or by dependabot

**Comment by Haruyzal** [comment]
Reverted target framework back to 7.0 - assuming that's what we're supposed to do as per our last discussion? Else please undo my revert x)

**Review by JonasSkjodt — APPROVED** [review]
Looks good, approved

**Review by Slug-Boi — APPROVED** [review]
Looks good. Gonna be great to have the test run on the new DB system

**Review by Alex-itu — APPROVED** [review]
Looks good, let's push it

**Pull request merged**
